Repository LauraVanesa06/PROYECTO-FORMATIVO, pull requests merged in 2025-04, with the labels that each got.

#30 Dashboard
  dashboard/img/test.png
  dashboard/index.html
  dashboard/style.css
Labels: dependencies

#37 Listo
  diagramas/Asociacion.png
  diagramas/Asociaciones.png
  diagramas/DIAGRAMAS.pdf
  diagramas/relacion.png
  diagramas/relaciones.png
Labels: enhancement

#55 fix
  dashboard/index.html
Labels: documentation
