Repository LauraVanesa06/PROYECTO-FORMATIVO, pull requests merged in 2025-05, with the labels that each got.

#64 Listo, los diagramas agregados
  docs/documentacion/css/estilos.css
  docs/documentacion/index.html
  docs/documentacion/informacion.html
Labels: documentation

#67 ready
  backend/app/assets/stylesheets/dashboard.css
  backend/app/controllers/dashboard_controller.rb
  backend/app/helpers/dashboard_helper.rb
  backend/app/views/dashboard/index.html.erb
  backend/app/views/layouts/application.html.erb
  backend/config/routes.rb
  backend/db/development.sqlite3
  backend/db/development.sqlite3-shm
  backend/db/development.sqlite3-wal
  backend/test/controllers/dashboard_controller_test.rb
Labels: dependencies

#125 sign up and forgot password
  backend/app/assets/stylesheets/application.css
  backend/app/controllers/usuarios/passwords_controller.rb
  backend/app/controllers/usuarios/registrations_controller.rb
  backend/app/helpers/usuarios/passwords_helper.rb
  backend/app/views/devise/passwords/new.html.erb
  backend/app/views/devise/registrations/new.html.erb
  backend/app/views/devise/sessions/new.html.erb
  backend/app/views/devise/shared/_links.html.erb
  backend/config/routes.rb
  backend/db/development.sqlite3
  backend/test/controllers/usuarios/passwords_controller_test.rb
Labels: documentation

#118 nuevo prograa flutter (ingresar valor, aplicar descuento)
  ferremateriales/lib/main.dart
  ferremateriales/lib/valor.dart
Labels: enhancement

#129 dashboard home design and more things
  backend/app/assets/images/background.png
  backend/app/assets/images/texture-dashboard.png
  backend/app/assets/images/texture-dashboard2.png
  backend/app/assets/stylesheets/dashboard.css
  backend/app/views/dashboard/clientes.html.erb
  backend/app/views/dashboard/index.html.erb
  backend/app/views/dashboard/inventario.html.erb
  backend/app/views/dashboard/proveedores.html.erb
  backend/app/views/dashboard/ventas.html.erb
  backend/db/development.sqlite3
Labels: documentation
