Repository LauraVanesa06/PROYECTO-FORMATIVO, pull requests merged in 2025-06, with the labels that each got.

#145 Feature/144
  backend/app/assets/stylesheets/dashboard.css
  backend/app/views/dashboard/index.html.erb
  backend/db/development.sqlite3-shm
  backend/db/development.sqlite3-wal
Labels: documentation

#153 Feature/147
  backend/db/seeds.rb
Labels: documentation

#174 Feature/161
  backend/app/assets/images/avatar.png
  backend/app/assets/images/candado.png
  backend/app/assets/images/degrade.png
  backend/app/assets/images/hexagono.png
  backend/app/assets/images/logo.jpg
  backend/app/assets/images/logo.png
  backend/app/assets/images/ojo-abierto.png
  backend/app/assets/images/ojo.png
  backend/app/assets/images/user.png
  backend/app/assets/stylesheets/application.css
  backend/app/assets/stylesheets/login.css
  backend/app/views/devise/registrations/edit.html.erb
  backend/app/views/devise/registrations/new.html.erb
  backend/app/views/devise/sessions/new.html.erb
  backend/app/views/devise/shared/_links.html.erb
  backend/app/views/layouts/application.html.erb
  backend/config/initializers/assets.rb
Labels: enhancement, dependencies

#198 done
  backend/app/assets/stylesheets/inventario.css
Labels: bug
