Repository LauraVanesa06/PROYECTO-FORMATIVO, pull requests merged in 2025-08, with the labels that each got.

#260 ngrok
  backend/config/environments/development.rb
Labels: enhancement

#262 Featrure/257
  backend/app/assets/stylesheets/application.css
  backend/app/controllers/application_controller.rb
  backend/app/controllers/cart_items_controller.rb
  backend/app/controllers/carts_controller.rb
  backend/app/controllers/dashboard_controller.rb
  backend/app/controllers/favorites_controller.rb
  backend/app/controllers/home_controller.rb
  backend/app/controllers/usuarios/registrations_controller.rb
  backend/app/helpers/favorites_helper.rb
  backend/app/models/cart.rb
  backend/app/models/cart_item.rb
  backend/app/models/favorite.rb
  backend/app/models/product.rb
  backend/app/models/user.rb
  backend/app/views/carts/show.html.erb
  backend/app/views/favorites/index.html.erb
  backend/app/views/home/contacto.html.erb
  backend/app/views/home/index.html.erb
  backend/app/views/home/producto.html.erb
  backend/app/views/layouts/application.html.erb
  backend/config/routes.rb
  backend/db/migrate/20250809234005_create_carts.rb
  backend/db/migrate/20250809234022_create_cart_items.rb
  backend/db/migrate/20250810003820_add_user_id_to_carts.rb
  backend/db/migrate/20250810034541_create_favorites.rb
  backend/db/schema.rb
  backend/test/controllers/favorites_controller_test.rb
  backend/test/fixtures/cart_items.yml
  backend/test/fixtures/carts.yml
  backend/test/fixtures/favorites.yml
  backend/test/models/cart_item_test.rb
  backend/test/models/cart_test.rb
  backend/test/models/favorite_test.rb
Labels: enhancement

#266 fix
  backend/config/routes.rb
Labels: documentation

#279 Feature/263
  PROYECTO-FORMATIVO.code-workspace
  backend/app/controllers/application_controller.rb
  backend/app/controllers/cart_items_controller.rb
  backend/app/models/cart.rb
  backend/app/models/cart_item.rb
  backend/app/models/product.rb
  backend/app/views/cart_items/create.turbo_stream.erb
  backend/app/views/cart_items/destroy.turbo_stream.erb
  backend/app/views/cart_items/update.turbo_stream.erb
  backend/app/views/carts/_cart_count.html.erb
  backend/app/views/carts/_cart_items.html.erb
  backend/app/views/carts/show.html.erb
  backend/app/views/home/index.html.erb
  backend/app/views/home/producto.html.erb
  backend/app/views/layouts/application.html.erb
  backend/config/routes.rb
Labels: bug, dependencies
